# Generated by Django 3.2.4 on 2021-06-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='ticket_order',
        ),
    ]
