# Generated by Django 3.2.4 on 2021-06-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteOrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('order_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delete_order_data',
            },
        ),
    ]
